### ISSUE TITLE
aggiungimi 

### ISSUE THREAD

**Issue by Silversurfero** [webcrumbs/javascript-crumbs#1]

**Comment by federicospini** [comment]
Ciao dragonjak,

Benvenuto al CVD Lab!

Avevamo chiesto di aprire le issues su cvdlab-cg/subscriptions: fai attenzione ;)

Completa il profilo con nome, cognome e mail così ci conosciamo meglio tutti!

Se non l'hai ancora fatto, installa git (necessario per poter usare questa piattaforma)
(segui questa semplice [guida](http://help.github.com/mac-set-up-git/))

Se hai installato git, prova a creare il tuo primo repository sul tuo account
(segui questa semplice [guida](http://help.github.com/create-a-repo/))

A presto :)
