### ISSUE TITLE
aggiungimi all'organizzazione

### ISSUE THREAD

**Issue by Faber89** [webcrumbs/javascript-crumbs#2]

**Comment by federicospini** [comment]
Ciao Faber89,

Benvenuto al CVD Lab!

Avevamo chiesto di aprire le issues su cvdlab-cg/subscriptions: fai attenzione ;)

Completa il profilo con nome, cognome e mail così ci conosciamo meglio tutti!

Se non l'hai ancora fatto, installa git (necessario per poter usare questa piattaforma)
(segui questa semplice [guida](http://help.github.com/mac-set-up-git/))

Se hai installato git, prova a creare il tuo primo repository sul tuo account
(segui questa semplice [guida](http://help.github.com/create-a-repo/))

A presto :)
