### ISSUE TITLE
add me please

### ISSUE THREAD

**Issue by ghost** [webcrumbs/javascript-crumbs#4]

**Comment by enricomarino** [comment]
Ciao Marcin,

Benvenuto al CVD Lab!

Avevamo chiesto di aprire le issues sul progetto [subsriptions](https://github.com/cvdlab-cg/subscriptions) 
nell'organizzazione per il corso di grafica computazionale [cvdlab-cg](https://github.com/cvdlab-cg): fai attenzione ;)

Completa il profilo con nome, cognome e mail così ci conosciamo meglio tutti!

Se non l'hai ancora fatto, installa git (necessario per poter usare questa piattaforma)
(segui questa semplice [guida](http://help.github.com/mac-set-up-git/))

Se hai installato git, prova a creare il tuo primo repository sul tuo account
(segui questa semplice [guida](http://help.github.com/create-a-repo/))

A presto :)
