### ISSUE TITLE
Iscrivimi

### ISSUE THREAD

**Issue by DaitanIII** [webcrumbs/javascript-crumbs#5]
richiesta iscrizione cvdlab
Corrado Antonio Cardone 
matricola 228091

**Comment by enricomarino** [comment]
Ciao Corrado,

Benvenuto al CVD Lab!

Grande! Hai già creato il tuo primo repository!

Sei stato aggiunto all'organizzazione github [cvdlab-cg](https://github.com/cvdlab-cg)
dove potrete pubblicare i progetti per il corso di Grafica Computazionale 
(prossimamente daremo indicazioni su come procedere)

A presto :)
