### ISSUE TITLE
Errore Infinite / Infinity

### ISSUE THREAD

**Issue by marcoliceti** [webcrumbs/javascript-crumbs#6]
Segnalo un piccolo refuso nell'esempio sulla funzione isFinite(): al posto della costante Infinity c'è scritto Infinite.

Analogamente, al posto di Number.POSITIVE_INFINITY [Number.NEGATIVE_INFINITY] è stato scritto Number.POSITIVE_INFINITE [Number.NEGATIVE_INFINITE].

P.s. Non so se queste segnalazioni sono desiderate (o desiderate in questa maniera: attraverso un Issue). Se sì, sarò lieto di segnalare altri errori, se ne trovo.

**Comment by enricomarino** [comment]
Grazie Marco :)

Stiamo pubblicando le dispense in una piattaforma di social coding proprio per questo! 

Prova a correggere gli errori trovati editando i file relativi direttamente da GitHub 
(in questo modo verrà creato un fork del progetto che troverai tra i tuoi repository)

Prova a segnalarci le modifiche effettuate sul tuo fork inviandoci una Pull Request
(il meccanismo di pull request lo affronteremo domani nella prossima lezione...)
